env:
  browser: true
  node: true
  es2021: true

parser: "@typescript-eslint/parser"

extends:
  - "eslint:recommended"
  - "airbnb-base"
  - "plugin:react/recommended"
  - "plugin:node/recommended"
  - "plugin:@typescript-eslint/recommended"

parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
  project: "./tsconfig.json"
  ecmaFeatures:
    jsx: true

plugins:
  - "react"
  - "@typescript-eslint"

rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-unused-vars": ["warn"]
  no-console: off
  import/extensions: off
  no-unused-vars: "warn"
  semi:
    - "error"
    - "always"
  quotes:
    - "error"
    - "double"

  react/prop-types: off

  indent:
    - "off"
    "@typescript-eslint/indent"
    - "error"
    - 2
