env:
  node: true
  es2021: true

parser: '@typescript-eslint/parser'

extends:
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:node/recommended'
  - 'plugin:@typescript-eslint/recommended'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: 'module'

plugins:
  - 'react'
  - '@typescript-eslint'

rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  no-console: off
  import/extensions: off
  no-unused-vars: 'warn'
  semi:
    - 'error'
    - 'always'
  quotes:
    - 'error'
    - 'double'

  react/prop-types: off
